### ISSUE TITLE
More Dice!

### ISSUE THREAD

**Issue by nandatanda** [r3tr0-Dev/DnD-20-sided-Dice#1]
This is a good start, and congrats on your first repo! The thing is, this class is not nearly powerful enough, which is why it took so many lines to produce this thing. So basically, when we create a class, we wanna encapsulate everything that makes it up inside of it. We wanna make one die class that handles all the die's fuctions.
```python
# your way
class MainDice:
    def __init__(self):
        self.position = Point(200, 130)
        self.image = Image(self.position, 'dice.png')
        return

    def create(self, wn):
        self.image.draw(wn)
        return
```
The thing about this is that it necessitates other classes and standalone functions to do the things that a die should rightly be able to do on its own, like roll or produce a random value.
```python
# my way
class D20():
    def __init__(self, x, y): # we take the position upfront, so we can move the die all at once.
        self.position = Point(x, y)
        self.image = Image(self.position, 'dice.png')
        self.number = 0
        self.sides = 20 # used in .roll()
        self.text = ''
        self.label = Text(self.position, self.text) # the textbox is now part of the die.

    def draw(self, window):
        self.label.setSize(20)
        self.label.setFill(color_rgb(255, 0, 0))
        self.label.draw(window)
        self.image.draw(window)
        return

    def roll(self): # we take the random number INSIDE the class
        self.number = randint(1, self.sides)
        self.text = str(self.number)
        return

    def update(self):
        self.label.setText(self.text)
        return

    def clear(self):
        self.label.setText('')
        return
```
Now you can control the entire die object, including the text box with `.draw(window)`, `.roll()`, `.update()`, and `.clear()`. The main function now would be super duper simple:
```python
winX = 400
winY = 400
winName = 'DnD Dice Generator'
window = GraphWin(winName, winX, winY)
die = D20(200, 130) # pass the position

die.draw(window)
while True:
    window.getMouse()
    die.roll()
    die.update()
    window.getMouse()
    die.clear()
```
Now the die class is much stronger and we literally saved half the code, ~40 lines against the original ~80. Not only that, the above class gives you the framework to start making multiple fully featured dice at one and also change the number of sides. Also, the int value of the latest roll is preserved, meaning you could take averages and other calculations. Hope you find that helpful, and I attached the file in a zip below in case you need it, although the entire contents are above. Happy coding and Merry Christmas, dude!

[d20.zip](https://github.com/r3tr0-Dev/DnD-20-sided-Dice/files/2706406/d20.zip)

**Comment by r3tr0-Dev** [comment]
Nice Thanks!!!
