### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by nandatanda** [r3tr0-Dev/DnD-20-sided-Dice#2]
We don't want to define what the collision range is in constants inside the collide method, because if the class changes, the method will need maintenance, which gives you what's called 'technical debt'. When you initialized your button class, you use an image, which takes arguments (anchor, location). Meaning that your x and y represent the center of the object. We need to take into account the width and height of the image itself, which is 84 x 46 px.
```python
class Button:
    def __init__(self):
        self.x = 200
        self.y = 325
        self.width = 84
        self.height = 46

        self.image = 'rollBtn.png'
        self.button = Image(Point(self.x, self.y), self.image)
        self.text = Text(Point(self.x, self.y), 'ROLL') # no return at end of inits!

    def collide(self, click): # take the click instead of the window
        clickX = click.getX()
        clickY = click.getY()
        leftX = self.x - (self.width / 2) # getting the bounds of the button.
        rightX = self.x + (self.width / 2) # if your button size changes, this will work w/o modification.
        topY = self.y - (self.height / 2)
        bottomY = self.y + (self.height / 2)

        if leftX < clickX < rightX: # if between x bounds
            if topY < clickY < bottomY: # if between y bounds
                return True # if both
        return False # if one or neither
```
The above will not only not break when the code is changed, but also is much more accurate about whether the button was pressed, because it's calculating the bounds on the spot. When we get a mouse click, we want it where we can see it, on the surface level of the main function. We don't want it buried inside of a method because it's a control flow object. In main:
```python
while True:
        click = wn.getMouse() # use proper variable names!
        if rollBtn.collide(click):
            myDice.roll()
            myDice.set()
```
Also, there are some formatting things, like:
`def __init__(self, x = 200, y = 200): # never use spaces in a default argument`

Maybe get an auto formatter. I set one up for VSCode, it's great. Good job again. I see what you were trying to do because you had prior knowledge of the thing's size, but collision is one place you DONT wanna do that, cause in a game the size of https://github.com/nandatanda/Bulletheck or bigger, you cant hunt down that small difference so easily, and you might even forget it's there. Try to write the methods of a class so that as long as the attributes are valid, it should just work.

**Comment by r3tr0-Dev** [comment]
oh ok I'll keep it in mind but I think for a simple check as to where  my mouse is clicking I find it a bit easier to just check the abs.. I really like what you did though I'll definitely keep that in mind. Thank you!

**Comment by nandatanda** [comment]
If you like the look of the absolute value statements, do it this way:
```python
def collide(self, click):
        clickX = click.getX()
        clickY = click.getY()
        dx = abs(clickX - self.x)
        dy = abs(clickY - self.y)

        if dx < self.width / 2:
            if dy < self.height / 2:
                return True
        return False
```
I feel like the other way is more human-readable.
